Issue/1121
MTES-MCT/resorption-bidonvilles pull request #220
Opened 2021-07-16 12:50 UTC by ch-benard

## 🧾 Ticket Trello
[Redirection systématique vers la page d'invitation depuis le formulaire de contact]( https://trello.com/c/JQNs6sJA)
[Notif mattermost pour invitation quelque soit l'objet du message depuis landing](https://trello.com/c/JQNs6sJA)

## 🛠 Description de la PR
**Info**: La branche initiale `issue/1107` correspondant à la première carte a été intégrée à la `branche issue/1121`, les deux sujets étant liés.
- La première carte conerne la redirection vers la page permettant d'nviter d'autres acteurs à décourvrir la platforme systématique, quelque soit le motif de la demande de contact. Auparavant, seules les demandes d'accès à la plateforme faisaient l'objet de cette redirection.
- La seconde carte consiste à préciser l'origine de l'invitation dans la notification Mattermost qui est déclechée à chaque saisie d'une invitation à rejoindre la plateforme.
- Deux bugs mineurs ont été corrigés au passage:
> *"Expected String, got Array for prop Icon"* concernant le composant `ui/Icon.vue`
> *"Expected String, got Number for prop rows"* concernant le composant `ui/form/input/TextArea.vue`

## 🚨 Notes pour la mise en production
Dans **Matomo**, créer deux exceptions permettant d'éviter le tracking des paramètres `first_name` et `last_name` dans les paramètres de requêtes.

2021-07-22 12:10 UTC, anis requested changes
Petites demandes d'améliorations.

2021-07-22 12:10 UTC, anis commented on packages/api/server/middlewares/validators/invite.js
> +        .notEmpty().bail().withMessage('L\'origine de l\'invitation est obligatoire'),
On peut rajouter ici une validation de la valeur de from, dans la mesure où c'est un enum

2021-07-22 12:10 UTC, anis commented on packages/api/server/controllers/inviteController.js
> +    let from = 'via une source non identifiable';
ce cas ne doit jamais arriver : il faut modifier le validator en ce sens

2021-07-22 12:10 UTC, anis commented on packages/api/server/mails/mails.js
> +                invitationUrl: `${invitationUrl}?email=${encodeURIComponent(recipient.email)}&first_name=${recipient.first_name}&last_name=${recipient.last_name}&from=push_mail&${utm}`,
il manque les `encodeURIComponent()` pour échapper `first_name` et `last_name`

2021-07-22 12:10 UTC, anis commented on packages/frontend/src/js/app/pages/Contact/index.vue
> +                        this.commonFields.last_name
Il manque `encodeURIComponent()`

2021-07-22 12:13 UTC, anis commented on packages/api/server/middlewares/validators/invite.js
> +        .notEmpty().bail().withMessage('L\'origine de l\'invitation est obligatoire'),
```
.custom((value) => {
    if (!['access_request', 'contact_others', 'push_mail'].includes(value)) {
        throw new Error('...');
    }
})
```

2021-07-22 13:16 UTC, ch-benard commented on packages/api/server/controllers/inviteController.js
> +    let from = 'via une source non identifiable';
Ok c'est corrigé.

2021-07-22 13:18 UTC, ch-benard commented on packages/api/server/mails/mails.js
> +                invitationUrl: `${invitationUrl}?email=${encodeURIComponent(recipient.email)}&first_name=${recipient.first_name}&last_name=${recipient.last_name}&from=push_mail&${utm}`,
C'est corrigé.

2021-07-22 13:19 UTC, ch-benard commented on packages/api/server/middlewares/validators/invite.js
> +        .notEmpty().bail().withMessage('L\'origine de l\'invitation est obligatoire'),
Ok. Elle a été ajoutée.

2021-07-22 13:26 UTC, ch-benard commented on packages/frontend/src/js/app/pages/Contact/index.vue
> +                        this.commonFields.last_name
Ok c'est corigé.

2021-07-23 06:54 UTC, ch-benard commented on packages/frontend/src/js/app/pages/Contact/index.vue
> +                                :showMandatoryStar="true"
Ok. J'ai supprimé les *

2021-07-26 15:21 UTC, merged