#minor (987) Appliquer le design system à la page du formulaire "créer un utilisateur"
MTES-MCT/resorption-bidonvilles pull request #248
Opened 2021-08-06 08:23 UTC by gaeldestrem

## 🧾 Ticket Trello
https://trello.com/c/8GGsG3Yc/987-appliquer-le-design-system-%C3%A0-la-page-du-formulaire-cr%C3%A9er-un-utilisateur

## 🛠 Description de la PR
Mise à jour de la route nouvel-utilisateur avec le nouveau design system. Reprise du layout de formulaire de contact

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/5053593/128480583-0d3e8698-cfad-4ba2-b00f-eb077905bb72.png)

2021-08-23 09:38 UTC, ch-benard approved these changes

2021-08-23 12:03 UTC, anis requested changes
Deux retours :
- obligatoire : le parcours de création d'un nouvel utilisateur depuis le formulaire de création d'un dispositif ne marche plus comme prévu (le champ "structure" est censé être pré-rempli avec la bonne association et en mode readonly)
- totalement optionnel : question sur la pertinence de mutualiser les champs de structure avec Contact pour éviter de répéter des trucs assez verbeux

2021-08-23 12:03 UTC, anis commented on packages/frontend/src/js/app/pages/UserCreate/index.vue
> +                    <PublicEstablishmentForm
C'est dommage de ne pas mutualiser ces champs avec `Contact/index.vue` non ?

2021-08-24 09:25 UTC, anis approved these changes

2021-08-24 15:25 UTC, merged