#minor (1163) Appliquer le design system à la fiche d'un utilisateur
MTES-MCT/resorption-bidonvilles pull request #249
Opened 2021-08-06 09:32 UTC by gaeldestrem

## 🧾 Ticket Trello
https://trello.com/c/C7uIzCj5/1163-appliquer-le-design-system-%C3%A0-la-fiche-dun-utilisateur

## 🛠 Description de la PR
Redesign de la fiche utilisateur

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/5053593/128490001-db0bbbb4-d2a6-48da-85c9-edb83125d038.png)

2021-08-23 12:48 UTC, ch-benard reviewed
Ok en ce qui me concerne.  RAS.

2021-08-24 09:54 UTC, anis requested changes
Petit retour sur l'état loading / erreur. Sinon nickel.

2021-08-24 09:54 UTC, anis commented on packages/frontend/src/js/app/pages/UserValidate/index.vue
> +                            >Envoyer un accès</Button
Il faudrait un état loading sur ces boutons non ?

2021-08-24 09:54 UTC, anis commented on packages/frontend/src/js/app/pages/UserValidate/index.vue
> +                error: null
J'ai l'impression que ce champ est renseigné mais jamais utilisé dans l'interface. Quand je simule une erreur côté API, il ne remonte aucune erreur sur l'interface.

2021-08-24 14:50 UTC, anis approved these changes

2021-08-24 15:28 UTC, merged