#patch (977) Appliquer le design system à l'annuaire
MTES-MCT/resorption-bidonvilles pull request #253
Opened 2021-08-16 15:59 UTC by gaeldestrem

## 🧾 Ticket Trello
https://trello.com/c/zc8Tvaso/977-appliquer-le-design-system-%C3%A0-la-sectionannuaire

## 🛠 Description de la PR
Appliquer le design system à l'annuaire

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/5053593/129593204-fe7aa03d-da86-422d-b074-cdb7e4b65af7.png)

![image](https://user-images.githubusercontent.com/5053593/129593253-219638a0-9c8e-43cc-81ab-a60f02dd93a2.png)

2021-08-23 14:37 UTC, ch-benard reviewed
Ok. Super la navigation rendue possible entre annuaire et liste/fiche utilisateur(s).

2021-08-24 12:19 UTC, anis requested changes
Quelques retours mineurs dont un qui me gêne vraiment : le hard-coding des ids d'organization_types.

2021-08-24 12:19 UTC, anis commented on packages/frontend/src/js/app/store/modules/directory.js
> +    const associationId = 8;
Ça m'a pas l'air dingue de hardcoder des ids de base ici. On n'a pas accès à la category pour filtrer sur le nom plutôt ?

2021-08-24 12:19 UTC, anis commented on packages/frontend/src/js/app/store/modules/directory.js
> +                console.log("setUserLocation", user.organization.location);
A retirer

2021-08-24 12:19 UTC, anis commented on packages/frontend/src/js/app/store/modules/directory.js
> +                commit("setDirectoryError", "Une erreur est survenue");
Ca ne vaudrait pas le coup de récupérer l'erreur renvoyée par l'API (s'il y en a une) ?
```commit("setDirectoryError", (error && error.user_message) || "Une erreur est survenue");```

2021-08-24 12:19 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationList/OrganizationCard.vue
> +            if (this.organization.type.id === 8) {
Même remarque que plus bas : je suis pas fun du hardcoding d'ids. Ce serait plus propre de s'appuyer sur le nom de la catégorie.

2021-08-24 12:19 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +                La structure demandé n'existe pas en base de données ou n'a pas
demandée*

2021-08-24 13:26 UTC, gaeldestrem commented on packages/frontend/src/js/app/components/GeoSearchbar/GeoSearchbar.vue
> +                    </slot>
J'ai juste encapsulé ce qu'il y'avait avant par un slot pour permettre de le personnaliser facilement : https://github.com/MTES-MCT/resorption-bidonvilles/blob/f8275b928ee05067bd9d33672b59ea068c86e162/packages/frontend/src/js/app/pages/OrganizationList/index.vue#L14

2021-08-24 14:48 UTC, anis approved these changes

2021-08-24 15:32 UTC, merged