#patch (1110) Amélioration cartographie au zoom
MTES-MCT/resorption-bidonvilles pull request #277
Opened 2021-09-01 14:11 UTC by ch-benard

## 🧾 Ticket Trello
https://trello.com/c/wh09FYWQ

## 🛠 Description de la PR
- Zoom sur les préfectures de département et région
- Positionnement par défaut sur la zone géographiques de la carte correspondant à la zone d'intérêt de l'organisme de l'utilisateur connecté
- Ajout par migration des coordonnées de localisation des régions et corrections de celles des départements qui étaient erronées
- Ajout du chef lieu de département et de régions dans les tables réspectives
- Suppression du calcul du centre des départements et régions qui donnent des positions parfois incohérentes (suivant le tracé de la zone géographique qui peut-être totalement asymétrique)

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/50863659/131685997-a9b74b33-8f49-489b-994a-315aeb93b734.png)

Après un clic sur le d&épartement de Haute-Garonne par exemple:
![image](https://user-images.githubusercontent.com/50863659/131686151-b548477a-1aab-4000-b5a6-d295f04110c5.png)

## 🚨 Notes pour la mise en production
- Exécuter les migrations suivantes:
     - 001110-00-update-departements-latLong.js
     - 001110-01-alter-regions_add_lat-lon.js
     - 001110-02-update-regions-latLong.js
     - 001110-03-alter-regions-add-fk_city.js
     - 001110-04-update-regions-add_fk_city.js
     - 001110-05-alter-table-departements-add-fk_city.js
     - 001110-06-update-departements-add_fk_city.js
     - 001110-07-alter-view-localized_organizations.js
- Les migrations assurent le rafraîchissement de la vue matérialisée ```localized_organisations```

2021-09-16 09:56 UTC, gaeldestrem requested changes
Un micro retour sur du lint mais sinon ça me parait bon :)

2021-09-16 09:56 UTC, gaeldestrem commented on packages/frontend/src/js/app/components/map/map.js
> +                        acc.departements[obj.departement.code] = {};
Je trouve ça plus clair de créer un objet en un call:
```
acc.departements[obj.departement.code] = {
   sites: 0,
   code: obj.departement.code,
   ...
};
```

Que tu peux probablement simplifié en 
```
acc.departements[obj.departement.code] = {
   ...obj.departement,
   sites: 0
};
```

2021-09-16 09:56 UTC, gaeldestrem commented on packages/frontend/src/js/app/components/map/map.js
> +                        acc.regions[obj.region.code] = {};
pareil

2021-09-17 09:23 UTC, ch-benard commented on packages/frontend/src/js/app/components/map/map.js
> +                        acc.departements[obj.departement.code] = {};
Mais oui, tu as totalement raison. C'est corrigé.

2021-09-17 09:23 UTC, ch-benard commented on packages/frontend/src/js/app/components/map/map.js
> +                        acc.regions[obj.region.code] = {};
Idem, ainsi que pour les *cities*

2021-09-17 09:46 UTC, gaeldestrem approved these changes
ça me semble bon, je laisse @anis faire une passe

2021-09-29 08:30 UTC, anis requested changes
- quelques changements à faire sur les migrations pour sécuriser la validité des données en base
- quelques remarques "esthétiques" sur la partie front

2021-09-29 08:30 UTC, anis commented on packages/api/db/migrations/001110-03-alter-regions-add-fk_city.js
> +        ),
Par ailleurs, il manque la clé étrangère de `regions.fk_city` vers `cities.code`.
```
queryInterface.addConstraint('regions', ['fk_city'], {
    type: 'foreign key',
    name: 'fk_regions_prefecture',
    references: {
        table: 'cities',
        field: 'code',
    },
    onUpdate: 'cascade',
    onDelete: 'restrict',
    transaction,
})
```

2021-09-29 08:30 UTC, anis commented on packages/api/db/migrations/001110-03-alter-regions-add-fk_city.js
> +    ),
Il faudra naturellement penser à supprimer la clé étrangère ici.
```
queryInterface.removeConstraint(
    'regions',
    'fk_regions_prefecture',
    {
        transaction,
    },
)
```

2021-09-29 08:30 UTC, anis commented on packages/api/db/migrations/001110-05-alter-table-departements-add-fk_city.js
> +    ),
Mêmes remarques que pour les régions : allowNull doit passer à `false` à la fin + il manque la clé étrangère `departements.fk_city` => `cities.code`

2021-09-29 08:30 UTC, anis commented on packages/frontend/src/js/app/components/map/map.js
> -import pointOnFeature from "@turf/point-on-feature";
Si on utilise plus @ turf, il faut peut-être le supprimer des nodes_modules ?

2021-09-29 08:30 UTC, anis commented on packages/frontend/src/js/app/components/map/map.js
> +                        : 0;
La condition est bizarre je trouve ici.
Tu peux pas utiliser `this.numberOfShantytownsBy.regions[key].sites` directement ?

2021-09-29 08:30 UTC, anis commented on packages/frontend/src/js/app/components/map/map.js
> +            Object.keys(this.numberOfShantytownsBy.regions).forEach(key => {
Tu pourrais probablement clarifier cette boucle en récupérant toutes les propriétés de `this.numberOfShantytownsBy.regions[key]` au début de chaque itération. Ça rendrait la lecture du reste de l'algo plus facile (notamment l'appel à circleWithText).

Un truc du genre :
```
const { sites: nbSites, latitude, longitude, chieftown } = this.numberOfShantytownsBy.regions[key];
```

2021-09-29 08:30 UTC, anis commented on packages/frontend/src/js/app/components/map/map.js
> +            Object.keys(this.numberOfShantytownsBy.departements).forEach(
Même remarques que pour les régions :
- ça pourrait être plus lisible en gettant les propriétés de `this.numberOfShantytownsBy.departements[key]` en haut de la boucle
- la condition sur `this.numberOfShantytownsBy.departements[key].sites` me paraît étrange

2021-10-02 04:13 UTC, merged