#minor (1203) Redesign page mon compte + Pouvoir éditer les coordonnées d'autres utilisateurs
MTES-MCT/resorption-bidonvilles pull request #282
Opened 2021-09-10 08:35 UTC by gaeldestrem

## 🧾 Ticket Trello
https://trello.com/c/CoxmR02j/1203-pouvoir-%C3%A9diter-les-coordonn%C3%A9es-des-utilisateurs-nom-pr%C3%A9nom-mail-tel-fonction-possible-uniquement-pour-les-administrateurs-nation

## 🛠 Description de la PR
Redesign page mon compte + Pouvoir éditer les coordonnées d'autres utilisateurs

## 📸 Captures d'écran
Mon compte : Lecture
![image](https://user-images.githubusercontent.com/5053593/132825133-daef5d77-c713-4461-bdd3-52b1bbb46f83.png)

Mon compte : Edition
![image](https://user-images.githubusercontent.com/5053593/132825166-0460344c-3fe6-49f8-8d5b-d10e47765205.png)

Compte d'un autre utilisateur
![image](https://user-images.githubusercontent.com/5053593/132825251-f3728f56-2c79-47f6-8e51-b4d8593f2d91.png)

Edition du compte d'un autre utilisateur:
![image](https://user-images.githubusercontent.com/5053593/132825288-0e0ef4c0-8568-4d16-948a-8a7ac9beec99.png)

Lien vers le compte d'un autre utilisateur (colonne gauche):
![image](https://user-images.githubusercontent.com/5053593/132825364-6760b90d-465a-4de9-b614-560fd0d6ca2b.png)

2021-09-16 13:27 UTC, anis requested changes
Super, ça va bien faciliter la vie d'Annie et Dimitri je pense !
Quelques petits commentaires au passage, rien d'important dans l'ensemble.

2021-09-16 13:27 UTC, anis commented on packages/api/server/loaders/routesLoader.js
> +        middlewares.auth.isSuperAdmin,
Il manque le "appVersion.sync" et "charte.check" en middleware.

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/router.js
> +    return role_id === "national_admin";
J'ai un peu peur que de faire référence à "national_admin" un peu partout vienne en travers du système de permission et pose problème plus tard.
Même si je comprends que ça rend les choses assez pénibles à mettre en place du coup. J'ai pas trop d'avis tranché sur la question, je pose mon inquiétude là.

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/helpers/api/user.js
> +export function edit(userId, data) {
j'aurais plutôt mis `userId` en deuxième paramètre, puisqu'il est facultatif contrairement à data

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/pages/Account/index.vue
> +            this.loading = true;
Il faudrait également passer `this.edit` à `false`, et `this.error` à `null` non ?

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/pages/Account/index.vue
> +                this.error = err;
Il serait préférable de supporter une éventuelle erreur retournée par l'api : `(err && err.user_message) || "Une erreur inconnue est survenue lors du chargement des données"` par exemple

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/pages/Account/index.vue
> +            L'utilisateur n'existe pas en base de données.
Est-ce qu'il ne faudrait pas afficher l'erreur retournée par l'api ici : `{{ error }}`.
Dans le cas `(!user && !loading)`, modifier `load()` pour générer une erreur après le try/catch : `if (!user) { this.error = "L'utilisateur n'existe pas en base de données."; }`.

Dans ce cas, le `v-if` devient simplement `v-if="error"`

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/pages/Account/AccountRead/AccountRead.vue
> +                        contact@resorption-bodonvilles.beta.gouv.fr
Peut-être passer l'adresse mail dans un `<a href="mailto:...`

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/pages/Account/AccountRead/AccountRead.vue
> +                        Si vous souhaitez changer notre mot de passe, cliquez
notre => votre

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/pages/Account/AccountEdit/AccountEdit.vue
> +                    id="phone"
Je me demande s'il ne faudrait pas mettre un rules=required ici, dans la mesure où on ne peut plus faire de demande d'accès sans son téléphone de toute façon. 🤔

2021-09-16 13:27 UTC, anis commented on packages/frontend/src/js/app/pages/Account/AccountEdit/AccountEdit.vue
> +            try {
Il manque `this.error = null`

2021-09-17 15:12 UTC, gaeldestrem commented
J'ai mis le téléphone obligatoire uniquement quand on édite son compte. J'ai peur que ça pose soucis lorsque Annie/Dimitri veuille éditer un profil et qu'ils aient pas leur numéro de tel

2021-09-22 08:26 UTC, merged