#minor (1171) Setup weekly mail report
MTES-MCT/resorption-bidonvilles pull request #295
Opened 2021-09-15 16:59 UTC by anis

## 🧾 Ticket Trello
https://trello.com/c/YRKXS9WZ/1171

## 🛠 Description de la PR
- Ajout d'un job qui s'exécute tous les lundis à 4h00 du matin
- Ce job exécute le service `activitySummary.sendAll()`
- Ce même service fetch :
- - fetch le rapport d'activités et la liste des utilisateurs à notifier via deux nouveaux modèles : `activityModel.get()` et `userModel.findDepartementSummarySubscribers()`
- - envoie les rapports d'activités aux utilisateurs nationaux, régionaux, et départementaux respectivement via trois méthodes séparées : `activitySummary.sendNationalSummary`, `activitySummary.sendRegionalSummary`, et `activitySummary.sendDepartementalSummary` (à noter que si aucune activité n'a lieu, les utilisateurs nationaux ne reçoivent rien, contrairement aux autres utilisateurs)
- Création d'un nouveau mail `activity_summary.mjml`

## 📸 Captures d'écran
- Mail départemental
![Capture d’écran 2021-09-15 à 18 59 19](https://user-images.githubusercontent.com/1801091/133477092-13173623-9d01-413d-9af3-db0f9487454b.png)

2021-09-16 10:56 UTC, gaeldestrem requested changes
Quelques remarques sur la PR:

- Il y'a une erreur dans les fonctions sendRegionalSummary, sendNationalSummary, sendDepartemental où les promises ne sont pas bien gérés je pense
- Si on envoie à tous les users, j'ai une crainte sur le fait que le script fasse un très grand nombre de calls à mailjet en parallèlle (500+). Il faudrait mieux utiliser une promise pool pour éviter d'avoir trop de call en parallèle car ça risque de nous poser des problèmes (promises qui se perdent/ timeout ou qu'on se fase rate limit au niveau de l'API par mailjet)
- J'ai fait quelques remarques sur ts que tu peux ignorer

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/app.ts
>  const Sentry = require('@sentry/node');
C'est pas une super bonne pratique d'utiliser des require en TS de mémoire mais j'imagine que c'est pour le faire progressivement, ça rajoute sans doute pas mal de taff '^^

 Ca a peut etre changé mais il me semble que les types ne sont pas exportés avec les require. La façon plus standard est: `import * as Sentry from '@sentry/node'`

C'est possible que ça gueule si Sentry ne fournit pas les types et dans ce cas, t'as probablement une lib npm @types/express

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/app.ts
> +            await agenda.every("00 00 04 * * 1", "send_activity_summary");
J'aurais plus envoyé les mails vers 7-8h. Idéalement, on veut etre en haut de la pile de mails quand l'utilisateur ouvre ses mails le matin

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/services/activitySummary/sendAll.ts
> +    await Promise.all([
Question con mais est-ce qu'on a aucun moyen de savoir si un job est allé au bout?

ie: si pour un user, on a un email ou une variable invalide et que mailjet renvoit une 400, je pense que ça stopperait tout le job nope?

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/services/activitySummary/sendDepartementalSummary.ts
> +            sendActivitySummary(subscriber, {
Je suis étonné que ca fonctionne, tu retournes pas la promise non ? Et je pense qu'il faudrait englober chaque send par un try/catch pour éviter qu'une 400 fasse tout planter

Edit: Si on envoie à 500 users, je pense pas non plus que mailjet kiffe les 500 call api en parallèlle. Il vaudrait mieux utiliser une promise pool (https://github.com/supercharge/promise-pool) pour avoir au max que 5/10 calls en parallèlle

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/services/activitySummary/sendRegionalSummary.ts
> +            sendActivitySummary(subscriber, {
Pareil, la promise n'est pas retourné

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/services/activitySummary/sendNationalSummary.ts
> +        subscribers.map((subscriber) => sendActivitySummary(subscriber, {
je pense que c'est mieux d'englober ça dans un try/catch pour chaque envoi

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/services/activitySummary/sendDepartementalSummary.ts
> +export default async (argFrom: Date, argTo: Date, summaries: ActivityNationalSummary, subscribers: Array<any>): Promise<Array<void>> => {
Il y'a des rules tslint qui empeche de mettre des any, c'est pas une super bonne pratique, c'est un peu comme ouvrir une boite de pandore, on a tendance a vite en mettre partout pour aller plus vite et plus rien est typé à la fin :D

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/models/activityModel/types/ActivityNationalSummary.ts
> +export type ActivityNationalSummary = Record<
FYI: Tu peux définir des interfaces plus proches du JS si tu préfères la syntaxe qu'utiliser des Record

```
export interface ActivityNationalSummary {
   [code: RegionCode]: {
      [departement: DepartementCode]: ActivityDepartementalSummary
   }
} 
```

2021-09-16 10:56 UTC, gaeldestrem commented on packages/api/server/services/activitySummary/sendDepartementalSummary.ts
> +import { ActivityNationalSummary } from "#server/models/activityModel/types/ActivityNationalSummary";
FYI: Tu peux aussi spécifier `import type { ActivityNationalSummary }  from ...`

2021-09-16 13:40 UTC, anis commented on packages/api/server/app.ts
>  const Sentry = require('@sentry/node');
C'était pour limiter le diff et faciliter la relecture mais c'est un diff léger donc c'est modifié

2021-09-16 13:41 UTC, anis commented on packages/api/server/app.ts
> +            await agenda.every("00 00 04 * * 1", "send_activity_summary");
OK, c'est changé

2021-09-16 13:43 UTC, anis commented on packages/api/server/models/activityModel/types/ActivityNationalSummary.ts
> +export type ActivityNationalSummary = Record<
Thanks, c'est plus lisible

2021-09-16 16:58 UTC, anis commented on packages/api/server/services/activitySummary/sendDepartementalSummary.ts
> +export default async (argFrom: Date, argTo: Date, summaries: ActivityNationalSummary, subscribers: Array<any>): Promise<Array<void>> => {
Soyons honnête, j'avais peur de rentrer dans un engrenage interminable mais t'as raison, c'est changé.
À noter que, pour avoir des dossiers "types" bien organisés j'ai dû créer de nouveaux dossiers "userModel" et "permissionModel".

2021-09-16 16:59 UTC, anis commented on packages/api/server/services/activitySummary/sendDepartementalSummary.ts
> +import { ActivityNationalSummary } from "#server/models/activityModel/types/ActivityNationalSummary";
Dans la mesure où le fichier ne définit que des types, je suis pas sûr de l'intérêt de cette syntaxe dans ce cas précis ?

2021-09-16 17:02 UTC, anis commented on packages/api/server/services/activitySummary/sendAll.ts
> +    await Promise.all([
Il me semble effectivement qu'une promise qui foire suffit à stopper tout le Promise.all, si toutefois certaines requêtes n'étaient pas encore parties.
Mais catch les erreurs résoud cette question.
Quant à savoir si un job est allé au bout ou pas, la seule solution serait de générer une notif. mattermost, un peu comme pour les backups finalement.

2021-09-16 17:03 UTC, anis commented on packages/api/server/services/activitySummary/sendAll.ts
> +    await Promise.all([
(seule solution qui me vienne à l'esprit*, y a sûrement des solutions de monitoring plus abouties)

2021-09-27 13:52 UTC, gaeldestrem approved these changes

2021-09-28 08:07 UTC, merged