#minor (1234) AJout d'un champ commentaires sur la fiche utilisateur
MTES-MCT/resorption-bidonvilles pull request #306
Opened 2021-09-22 14:02 UTC by ch-benard

## 🧾 Ticket Trello
https://trello.com/c/OSHZQChD

## 🛠 Description de la PR
- Champ *commentaire* réservé aux administrateurs nationaux
- Ajout d'un composant *UserValidateComment*
- Création d'une route réservée au administrateurs nationaux pour mettre à jour le champ *admin_comments* de la table *users*
- Ajout des méthodes requises dans le modèle et le contrôleur de *users* pour mettre à jour le champ *admin_comments*.

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/50863659/134353064-3b38a47e-c631-474c-8ce0-42def20f3f60.png)

## 🚨 Notes pour la mise en production
- Une migration à exécuter: *001234-01-add_admin_comments_to_users.js*

2021-09-23 08:18 UTC, anis reviewed
Relu mais pas testé.
Aucun commentaire bloquant, ça a l'air fonctionnel.
Que des commentaires sur la structure du code.

2021-09-23 08:18 UTC, anis commented on packages/api/server/controllers/userController.js
> +        const user = await models.user.findOne(userId, { auth: true });
C'est le validator middleware qui est censé faire cette requête (et éventuellement répondre une erreur si user = null)

2021-09-23 08:18 UTC, anis commented on packages/api/server/controllers/userController.js
> +        }
Idem, il faut un validator middleware pour trim la valeur et retourner une erreur en cas de problème

2021-09-23 08:18 UTC, anis commented on packages/api/server/controllers/userController.js
> +                    developer_message: error.message,
Le developer_message est un reliquat d'une vieille idée, mais ce n'est pas exploité, pas besoin de le préciser.

2021-09-23 08:18 UTC, anis commented on packages/api/server/models/userModel.js
> +            }
Je pense que la couche modèle doit se contenter de faire la requête qu'on lui demande, sans faire de validation de donnée (c'est à la charge du contrôleur / service qui fait l'appel).
Je ne garderais que le `await database.query(...)`. Par ailleurs, le paramètre `comment` pour n'être qu'une string au lieu d'un objet non ?

2021-09-23 08:18 UTC, anis commented on packages/api/server/models/userModel.js
> +            }
Au-delà de ça, effectivement j'aurais utilisé la méthode "update" déjà existante.

2021-09-23 08:18 UTC, anis commented on packages/frontend/src/js/app/pages/UserValidate/UserValidateComment/UserValidateComment.vue
> +                this.commentError = response.user_message;
Si jamais l'erreur n'est pas côté API (ou une erreur 500 sans `user_message`) : `this.commentError = response && response.user_message || "Une erreur inconnue est survenue";`.

2021-09-23 16:20 UTC, ch-benard commented on packages/api/server/controllers/userController.js
> +                    developer_message: error.message,
Ok, j'ai supprimé la propriété  `developer_message` des objets `error`.

2021-09-23 16:21 UTC, ch-benard commented on packages/api/server/controllers/userController.js
> +        }
Le validator `userComments.js` a été créé.

2021-09-23 16:22 UTC, ch-benard commented on packages/api/server/controllers/userController.js
> +        const user = await models.user.findOne(userId, { auth: true });
Ok, le validator `userComments.js` a été créé.

2021-09-23 16:23 UTC, ch-benard commented on packages/api/server/models/userModel.js
> +            }
Effectivement, j'ai supprimé les contrôles qui sont déportés côté contrôleur et validator.

2021-09-29 08:35 UTC, anis commented on packages/api/server/loaders/routesLoader.js
> +        middlewares.appVersion.sync,
Renommer en `/users/:id/admin_comments`.
Renommer le validator également.
Manque le `charte.check`.

2021-09-29 09:39 UTC, anis requested changes
J'avais beaucoup de retours donc j'ai fait une PR feedback ici : https://github.com/MTES-MCT/resorption-bidonvilles/pull/316
Je te laisse regarder les changements que je propose et commenter si besoin. Une fois OK, merger ma PR feedback, puis on pourra merger cette PR.

2021-10-02 04:44 UTC, merged