Issue/1283
MTES-MCT/resorption-bidonvilles pull request #361
Opened 2021-11-17 15:58 UTC by ch-benard

## 🧾 Ticket Trello
https://trello.com/c/hzFOPcBr

## 🛠 Description de la PR
- Création d'un script de mutation pour ajouter les champ `being_funded` (*fait l'objet d'un financement*) et `being_funded_at` (*date de la mise à jour du statut du financement*) indiquant si une organisation (structure) fait l'objet d'un financement ou non
- Ajout d'un signe **€** sur la ligne de la structure qui fait l'objet d'un financement dans l'annuaire
- Ajout d'un formulaire d'édition des organisations (structures) permettant d'indiquer si une structure fait l'objet d'un financement de la DIHAL
- Création d'une route côté API pour la mise à jour partielle de l'organisation

## 📸 Captures d'écran
- Formulaire d'édition
![image](https://user-images.githubusercontent.com/50863659/142233051-6496f9bb-5a1e-46b0-9bf6-0c5af41bdcb1.png)

- Liste avec indication du financement (signe **€** présent)
![image](https://user-images.githubusercontent.com/50863659/142233320-d9a5a8e0-cf49-437a-979b-5ccba888d6e0.png)

## 🚨 Notes pour la mise en production
- Exécuter le script de migration `20211103-1283-01-add_being_funded_to_organizations.js`

2021-11-18 10:38 UTC, anis requested changes

2021-11-18 10:38 UTC, anis commented on packages/api/server/controllers/organizationController.js
> +            await models.organization.updateBeingFunded(paramId, data);
Il ne faut plus utiliser `models....` mais importer les méthodes directement tout en haut du fichier.

Rajouter un truc du genre :  
`const { updateBeingFunded, findOneById } = require('#server/models/organizationModel');`

2021-11-18 10:38 UTC, anis commented on packages/api/server/controllers/organizationController.js
> +        const organization = await models.organization.findOneById(paramId);
Ne plus utiliser `models...` (voir plus bas)

2021-11-18 10:38 UTC, anis commented on packages/api/server/models/organizationModel/updateBeingFunded.js
> +    });
Je sais que c'est un biais qu'il y a eu par le passé mais les modèles ne devraient avoir aucune logique et accepter les données en entrée sans filtre.

C'est d'autant plus vrai ici que ta fonction s'appelle "updateBeingFunded" et n'autoriser que deux propriétés donc tu peux écrire directement :
```
UPDATE organizations SET being_funded = :being_funded, being_funded_at = :being_funded_at WHERE organization_id = :organizationId
```

C'est la reponsabilité du contrôleur de passer les bonnes données pour que la requête ne foire pas.

2021-11-18 10:38 UTC, anis commented on packages/api/server/models/organizationModel/updateBeingFunded.js
> +    }
Pareil, pas besoin de surcharger le modèle en logique : ce n'est pas au modèle de décider que l'absence d'une structure soit une erreur. À la rigueur on peut return l'information et laisser le contrôleur décider de si ça relève d'une erreur ou s'il faut ignorer.

En l'occurrence je supprimerais simplement tout ce `if`.

2021-11-18 10:38 UTC, anis commented on packages/api/server/models/organizationModel/updateBeingFunded.js
> +    }
Pas besoin de vérifier ce genre de choses, c'est de la responsabilité du contrôleur

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
>      }
Je ne comprends pas l'intérêt de faire ça dans la mesure où le `load()` fetch tout l'annuaire. Un changement d'id ne provoquera aucun rechargement de données ?
En revanche, un changement de la valeur de `$route.params.id` provoquera probablement un changement de la valeur de la computed property `organization`, et donc le contenu de la page.

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +            loading: false,
loading n'est jamais passé à `true`, à supprimer

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +            error: null
error est inutilisé, à supprimer

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +        </LoadingError>
Ce cas n'existe pas, à supprimer

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> -import PrivateContainer from "#app/components/PrivateLayout/PrivateContainer";
Pourquoi avoir supprimé le PrivateContainer ? Il ne fournissait pas un layout nécessaire au reste de la page ?

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/utils/common.js
> +}
l'idée c'était de mettre un fichier `formatDate.js` et un fichier `isCurrentUserNationalAdmin` dans ce dossier `utils` ;)

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/utils/common.js
> +}
Par ailleurs, il existe déjà une fonction formatDate dans window.App. Voir une utilisation dans `pages/TownDetails/TownDetailsCovidCommentsSidePanel.vue`

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +            />
Cette solution me semble affreusement sur-compliquée par rapport au besoin. En gardant la page telle qu'elle était et en rajoutant simplement deux champs (visibles uniquement par l'admin national), ça faisait le même travail sans dupliquer autant de choses en deux composants séparés pourtant si similaires.
D'autant plus que ça ne sert qu'aux admins nationaux !

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationList/OrganizationCard.vue
> -        <router-link :to="`/annuaire/${organization.id}`">
pourquoi avoir retiré le `/` au début ? je crois bien qu'il est plutôt préférable de le laisser pour éviter des edge cases qui interpréteraient le chemin comme relatif

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/helpers/api/organization.js
> +    return putApi(`/organizations/${organizationId}/funded-status`, data);
refléter les changements demandés côté api (voir routesLoader)

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/helpers/api/organization.js
> +
Inutilisé à ma connaissance, à supprimer

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/pages/OrganizationDetails/OrganizationEdit/OrganizationEdit.vue
> +                this.$store.commit("updateOrganization", updatedOrganization);
utiliser `updateOrganization.data` (voir ma remarque côté api dans le retour du contrôleur)

2021-11-18 10:38 UTC, anis commented on packages/frontend/src/js/app/store/modules/directory.js
> +                    updatedOrganization.being_funded_at;
Tu peux être plus générique :
`state.items[index] = { ...state.items[index], ...updatedOrganization };`

2021-11-18 12:05 UTC, ch-benard commented on packages/api/server/middlewares/validators/editOrganization.js
> +}
Supprimé

2021-11-18 12:06 UTC, ch-benard commented on packages/api/server/loaders/routesLoader.js
> +        // middlewares.validation,
Fait.

2021-11-18 12:07 UTC, ch-benard commented on packages/api/server/middlewares/validators/editOrganization.js
> +        .customSanitizer(fromIntToBoolSanitizer),
Corrigé.

2021-11-18 12:09 UTC, ch-benard commented on packages/api/server/middlewares/validators/editOrganization.js
> +        .toDate()
Corrigé. J'utilise `.isISO8601` pour valider la date.

2021-11-18 12:10 UTC, ch-benard commented on packages/api/server/middlewares/validators/editOrganization.js
> +            today.setHours(0, 0, 0, 0);
Plus utile en utilisant `.isISO8601()` qui permet de conserver l'heure.

2021-11-18 12:11 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +/* eslint-disable no-console */
Fait.

2021-11-18 12:11 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +            res.status(500).send({
Corrigé.

2021-11-18 12:13 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +                    developer_message: `Organization #${paramId} does not exist`,
Corrigé dans la méthode `updateFundedStatus`

2021-11-18 12:47 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +        const organization = await models.organization.findOneById(paramId);
Corrigé.

2021-11-18 12:47 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +            await models.organization.updateBeingFunded(paramId, data);
Corrigé.

2021-11-18 12:47 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +                    developer_message: error.message,
Corrigé.

2021-11-18 12:48 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +            await models.organization.updateBeingFunded(paramId, data);
Corrigé.

2021-11-18 12:48 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +        const organization = await models.organization.findOneById(paramId);
Corrigé.

2021-11-18 12:55 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +        </LoadingError>
Corrigé.

2021-11-18 12:55 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +            error: null
Corrigé.

2021-11-19 13:12 UTC, ch-benard commented on packages/api/server/models/organizationModel/updateBeingFunded.js
> +    });
J'ai transféré le contrôle de l'identifiant de l'organisation côté contrôleur et simplifier la requête de mise à jour au plus simple.

2021-11-19 13:12 UTC, ch-benard commented on packages/api/server/loaders/routesLoader.js
> +    app.put(
On utilise désormais PATCH

2021-11-19 13:14 UTC, ch-benard commented on packages/api/server/models/organizationModel/updateBeingFunded.js
> +    });
Le contrôle du paramètre corrspondant à l'identifiant de l'organisatiuon est fait côté contrôleur et la requête a été simplifiée.

2021-11-19 13:15 UTC, ch-benard commented on packages/api/server/models/organizationModel/updateBeingFunded.js
> +    }
Corrigé.

2021-11-19 13:16 UTC, ch-benard commented on packages/api/server/models/organizationModel/updateBeingFunded.js
> +    }
Corrigé.

2021-11-19 13:16 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> -import PrivateContainer from "#app/components/PrivateLayout/PrivateContainer";
C'est corrigé.

2021-11-19 13:17 UTC, ch-benard commented on packages/frontend/src/js/helpers/api/organization.js
> +    return putApi(`/organizations/${organizationId}/funded-status`, data);
Corrigé. Utilisation du verbe PATCH.

2021-11-19 13:18 UTC, ch-benard commented on packages/frontend/src/js/helpers/api/organization.js
> +
C'est corrigé.

2021-11-19 13:48 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
>      }
Effectivement. Supprimé.

2021-11-19 13:48 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationDetails/index.vue
> +            loading: false,
Supprimé.

2021-11-19 14:29 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationDetails/utils/common.js
> +}
Ok, corrigé. J'ai une erreur qui se décleche quand j'utilise `App.formatDate(...)` ; je conserve donc la fonction dans `./utils`

2021-11-19 16:07 UTC, ch-benard commented on packages/api/server/controllers/organizationController.js
> +                being_funded_at,
Oui, c'est corrigé.

2021-11-19 16:08 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationDetails/OrganizationEdit/OrganizationEdit.vue
> +                this.$store.commit("updateOrganization", updatedOrganization);
C'est corrigé.

2021-11-19 16:08 UTC, ch-benard commented on packages/frontend/src/js/app/store/modules/directory.js
> +                    updatedOrganization.being_funded_at;
Effectivement. Je n'ai pas encore le réflexe de simplifier avec cette syntaxe.

2021-11-22 21:02 UTC, ch-benard commented on packages/api/db/migrations/20211103-1283-01-add_being_funded_to_organizations.js
> +                defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
Il s'agit d'une date technique non saisie mais calculée. Donc pas nécessaire.

2021-11-22 21:03 UTC, ch-benard commented on packages/api/db/migrations/20211103-1283-01-add_being_funded_to_organizations.js
> +            `CREATE MATERIALIZED VIEW localized_organizations AS
`CREATE OR REPLACE` ne fonctionne que pour les vues, et non pour les vues matérialisées, du moins selon mes connaissances de PostgreSQL.

2021-11-22 21:03 UTC, ch-benard commented on packages/api/db/migrations/20211103-1283-01-add_being_funded_to_organizations.js
> +            `CREATE MATERIALIZED VIEW localized_organizations AS
Ok, c'est corrigé.

2021-11-22 21:05 UTC, ch-benard commented on packages/api/db/migrations/20211103-1283-01-add_being_funded_to_organizations.js
> +            `CREATE MATERIALIZED VIEW localized_organizations AS
Je me suis permis de nommer les scripts de migrations de façon à faire référence aux scripts qui les utilisent.

2021-11-22 21:05 UTC, ch-benard commented on packages/frontend/src/js/app/pages/OrganizationList/OrganizationCard.vue
> -        <router-link :to="`/annuaire/${organization.id}`">
Un "bug de saisie" de ma part. C'est restauré.

2021-11-22 21:46 UTC, ch-benard commented on packages/api/server/middlewares/validators/editOrganization.js
> +        .exists({ checkNull: true }).bail().withMessage('Le champ "Date de mise à jour" est obligatoire')
Il s'agit d'un champ part défaut à "Non". Vu en standup le 22/11/2021.

2021-12-01 08:25 UTC, merged