#minor (1275) infinite scrolling
MTES-MCT/resorption-bidonvilles pull request #389
Opened 2022-01-04 10:10 UTC by gregoirethomazeau

## 🧾 Ticket Trello
https://trello.com/c/onI2HPi6/1275-derni%C3%A8res-activit%C3%A9s-passer-en-infinite-scroll-en-prenant-en-compte-les-filtres

## 🛠 Description de la PR
Les dernières activités sont maintenant affichées en infinite scrolling. Au lieu de charger tout l'historique dans le store, puis d'appliquer les filtres côté front, dorénavant on va les chercher au fur et à mesure et les filtres sont appliqués directement dans la requête SQL.
Les changements majeurs sont côté API, ce qui a nécessité des adaptations côté front pour l'affichage des 5 dernières activités  dans l'onglet 'Liste des sites' ainsi que pour l'affichage des commentaires covid dans l'onglet 'Covid19'.
## 📸 Captures d'écran

## 🚨 Notes pour la mise en production

2022-01-12 10:41 UTC, anis requested changes

2022-01-12 10:41 UTC, anis commented on packages/frontend/src/js/app/pages/History/History.vue
> +                window.removeEventListener("scroll", this.reachBottom);
pour simplifier la gestion du listener (qui est un risque de fuite mémoire si on en ajoute plein et qu'on oublie de les retirer) je ne le retirerais pas ici, et je changerais la logique de "reachBottom" pour ne pas faire d'appel API si on a atteint la fin de la liste

2022-01-12 10:41 UTC, anis commented on packages/frontend/src/js/app/pages/covid/covid.js
> +                9999999999,
un peu violent 😂
d'habitude, pour ce genre de cas, il y a deux options :
- créer un nouveau paramètre, booléen, qui permet de dire qu'on veut tous les items (auquel cas, le paramètre nombreActivites est ignoré si toutefois il était renseigné)
- garder uniquement le paramètre nombreActivites et faire en sorte que la valeur spéciale `-1` veuille dire "charger tous les items"

Ça évite de devoir mettre un nombre purement arbitraire comme ici :)

2022-01-12 10:41 UTC, anis commented on packages/frontend/src/js/app/pages/TownsList/TownsList.vue
> +            console.log(tempLastActivities);
console.log() à supprimer

2022-01-12 10:41 UTC, anis commented on packages/frontend/src/js/app/pages/TownsList/TownsList.vue
> +                console.log(currentDate - activity.date);
console.log() à supprimer

2022-01-12 10:41 UTC, anis commented on packages/frontend/src/js/app/pages/TownsList/TownsList.vue
> +            console.log(this.lastActivities);
console.log() à supprimer

2022-01-12 10:41 UTC, anis commented on packages/frontend/src/js/app/pages/TownsList/TownsList.vue
> +            locationCode: null,
Je crois que tu n'as pas besoin de déclarer ces variables dans data(), ça peut être de simples variables locales à ta méthode `getActivities()`

2022-01-12 10:41 UTC, anis commented on packages/frontend/src/js/app/pages/TownsList/TownsList.vue
> +            }
je ne suis pas sûr de ça, tu n'es pas censé passer la location qui est dans la barre de filtre géographique ?

2022-01-12 10:41 UTC, anis commented on packages/api/server/models/shantytownModel/getHistory.js
> +
à retirer

2022-01-12 12:28 UTC, gregoirethomazeau commented on packages/frontend/src/js/app/pages/TownsList/TownsList.vue
> +            }
si complètement, à revoir complètement

2022-01-12 12:32 UTC, gregoirethomazeau commented on packages/frontend/src/js/app/pages/History/History.vue
> +                            id="infinite_scroll"
je l'avais mis pour tester quelque chose, mais c'est inutile à présent, je le retire

2022-01-14 09:44 UTC, gregoirethomazeau commented on packages/api/server/models/highCovidCommentModel/getHistory.js
> +    const whereLastDate = `${where.length > 0 ? 'AND' : 'WHERE'} comments.created_at < '${lastDate}'`;
En fait dans shantytownModel/getHistory le where étant utilisé avec le mot clé 'OR', je ne pouvais pas ajouter mes conditions dans le tableau where. Après ça je ne me suis plus posé la question pour les autres fichiers getHistory mais effectivement ici c'est préférable d'inclure dans le where, je vais corriger

2022-02-10 12:49 UTC, merged