#patch (1324) ajout canal mattermost intervenants déclarés
MTES-MCT/resorption-bidonvilles pull request #390
Opened 2022-01-04 15:36 UTC by gregoirethomazeau

## 🧾 Ticket Trello
https://trello.com/c/tDm2ndGV/1324-cr%C3%A9er-un-canal-mattermost-intervenantsd%C3%A9clar%C3%A9s-qui-permettrait-de-suivre-au-fur-et-mesure-les-intervenants-qui-ont-cliqu%C3%A9-sur-ji

## 🛠 Description de la PR
- Création du canal mattermost et de deux trigger, selon qu'un utilisateur se déclare intervenant sur un site, ou qu'il cesse d'intervenir.
- Correction d'une petite coquille concernant la notification d'un nouvel utilisateur.

## 📸 Captures d'écran
<img width="1099" alt="Capture d’écran 2022-01-04 à 16 33 21" src="https://user-images.githubusercontent.com/94321132/148083427-5e651b87-ff1b-441f-bd0b-274eae457a25.png">

## 🚨 Notes pour la mise en production

2022-01-10 09:32 UTC, anis requested changes
Petite remarque d'ordre d'instructions.

2022-01-10 09:32 UTC, anis commented on packages/api/server/controllers/townController/removeActor.js
> +
Il vaut mieux mettre la notif _après_ la requête SQL : le risque étant que la notif mattermost parte, mais que la requête SQL échoue, faisant que ta notif annonce une mauvaise info.

2022-01-10 09:32 UTC, anis commented on packages/api/server/controllers/townController/addActor.js
> +
Il vaut mieux mettre la notif après la requête SQL : le risque étant que la notif mattermost parte, mais que la requête SQL échoue, faisant que ta notif annonce une mauvaise info.

2022-01-10 10:05 UTC, merged

2022-01-11 08:10 UTC, ch-benard reviewed
Vu