#patch (1421)  Afficher le nombre d'utilisateurs connectés dans la vue d'ensemble
MTES-MCT/resorption-bidonvilles pull request #503
Opened 2022-05-04 15:35 UTC by ch-benard

## 🧾 Ticket Trello
https://trello.com/c/YVPoSchJ

## 🛠 Description de la PR
**Côté API**
- Modification de la méthode  `getStats` du modèle `statsModel` pour remplacer le calcul du nombre d'utilisateurs par le nombre d'utilisateurs uniques connectés.
- Adaptation de la méthode `decomposeForDiagram`
** Côté Frontend**
- Adaptation de l'utilitaire `formatStats` utilisé dans le store par le module `dashboard` pour initialiser l'élémént `globalStats` fournissant les données à afficher au composant 'DashboardGlobalVueList`

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/50863659/166715218-00498f5d-7796-4760-863e-fb847a7bbaae.png)

## 🚨 Notes pour la mise en production
- Ràs

2022-05-04 15:46 UTC, anis commented on packages/api/server/models/statsModel/getStats.js
> +                localized_organizations lo ON u.fk_organization = lo.organization_id
C'est

2022-05-04 15:59 UTC, anis requested changes

2022-05-04 15:59 UTC, anis commented on packages/api/server/models/statsModel/getStats.js
> +                localized_organizations lo ON u.fk_organization = lo.organization_id
Tu peux probablement n'intégrer ces left join que s'il y a un where (pour optimiser le temps de la requête)

2022-05-04 15:59 UTC, anis commented on packages/api/server/models/statsModel/getStats.js
> +                fk_user`,
Pour faciliter l'exploitation derrrière, tu peux probablement générer le total par semaine plus facilement ici dans la requête SQL que dans `decomposeForDiagram`.
Ca donne quelque chose de ce genre :
```
SELECT
  COUNT(DISTINCT fk_user),
  CONCAT(EXTRACT(week from datetime), '/', EXTRACT(year from datetime)) AS week
FROM user_navigation_logs
GROUP BY CONCAT(EXTRACT(week from datetime), '/', EXTRACT(year from datetime))
ORDER BY CONCAT(EXTRACT(week from datetime), '/', EXTRACT(year from datetime)) ASC;
```

2022-05-04 15:59 UTC, anis commented on packages/api/server/models/statsModel/getStats.js
> +                fk_user`,
À voir avec JP s'il faut compter les admins nationaux dans ce total ou pas (si on s'aligne sur nos WAU affichés, il faudrait les ignorer : `WHERE users.fk_role IS NULL OR users.fk_role <> 'national_admin'`

2022-05-04 16:30 UTC, ch-benard commented on packages/api/server/models/statsModel/getStats.js
> +                fk_user`,
Intéressant. Mais l'affichage dans la vue d'ensemble est fait non pas par semaine calendaire mais par semaine glissante (au sens de 7 jours consécutifs). Chaque semaine de référence pour l'affichage des composants `bar` est calculée depuis le jour courant. Voir [cette méthode](https://github.com/MTES-MCT/resorption-bidonvilles/blob/develop/packages/api/server/models/statsModel/_common/getArrayOfDates.js).

2022-05-05 07:38 UTC, ch-benard commented on packages/api/server/models/statsModel/getStats.js
> +                localized_organizations lo ON u.fk_organization = lo.organization_id
Oui, c'est pas bête. J'ai corrigé.

2022-07-11 08:54 UTC, merged