#minor (1467) Mettre en avant graphiquement la section dans laquelle on se trouve
MTES-MCT/resorption-bidonvilles pull request #522
Opened 2022-05-23 14:19 UTC by ch-benard

## 🧾 Ticket Trello
https://trello.com/c/60OlkTvI

## 🛠 Description de la PR
- Wording: 
    - **"Annuaire"** devient **"Communauté"** dans le barre de navigation
    - **"Annuaire"** devient **"Découvrez la communauté"** dans l'entête de la page de l'annuaire
- L'item de la barre de navigation correspondant à la page visitée est mis en relief (couleur `primary` + "soulignement" de l'élément

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/50863659/170277043-19f77adc-5311-428b-aaf0-1a92e2ccc8f2.png)

## 🚨 Notes pour la mise en production
Ràs

2022-05-24 18:35 UTC, anis requested changes

2022-05-24 18:35 UTC, anis commented on packages/frontend/webapp/src/js/app/layouts/Navbar/Navbar.vue
> +            */
Retirer

2022-05-24 18:35 UTC, anis commented on packages/frontend/webapp/src/js/app/layouts/Navbar/Navbar.vue
> +}
L'idée était de n'utiliser des classes custom *que* pour ce que tailwind ne peut pas fournir ! En l'occurrence les background-color me semblent faisables sans classes custom.

2022-05-24 18:35 UTC, anis commented on packages/frontend/webapp/src/js/app/pages/UserList/UserListHeader/index.vue
> +                        Découvrez la communauté
Un peu surpris par ce changement, je ne comprends pas du ticket qu'il faille changer le wording ?

2022-05-24 18:35 UTC, anis commented on packages/frontend/webapp/src/js/app/layouts/Navbar/Navbar.vue
> +            console.log(`item.links: ${JSON.stringify(item.links)}`);
console.log à retirer

2022-05-24 18:35 UTC, anis commented on packages/frontend/webapp/src/js/app/layouts/Navbar/Navbar.vue
> +                // this.$router.currentRoute.path === target ||
commentaire à retirer

2022-05-24 18:35 UTC, anis commented on packages/frontend/webapp/src/js/app/layouts/Navbar/Navbar.vue
> +                ) ||
J'aurais inversé la logique : plutôt que de lister toutes les pages liées à un item du menu, j'aurais rajouté, pour chaque page, le nom de l'item du menu auquel elle se rattache.
L'idée étant qu'il est moins probable d'oublier, quand on crée une page, d'indiquer son item du menu, que de penser à le rajouter à la liste.

2022-05-24 18:49 UTC, anis commented on packages/frontend/webapp/src/js/app/layouts/Navbar/Navbar.vue
> +                ) ||
D'autant plus que toute cette mécanique était déjà en place !

2022-05-24 18:51 UTC, anis commented on packages/frontend/webapp/src/js/app/layouts/Navbar/Navbar.vue
> +    border-bottom-color: #000091;
Petit soucis pour le cas de l'onglet covid : la barre du bas devrait être rouge !

2022-05-25 08:38 UTC, ch-benard reviewed
Merci pour les dernières corrections @anis

2022-06-15 10:21 UTC, merged