#patch (1465) Ajout des sites fermés dont la population se réinstallerait sur le site en cours
MTES-MCT/resorption-bidonvilles pull request #535
Opened 2022-06-21 14:45 UTC by ch-benard

## 🧾 Ticket Trello
https://trello.com/c/idG68HHD

## 🛠 Description de la PR
-  Changer le wording de la question : remplacer "S'agit-il d'une réinstallation ?" par "Tout ou partie des habitants viennent-ils d'un ou plusieurs sites récemment fermés ?"
- Suggérer les sites fermés durant les 3 derniers mois à l'échelle du département, permettre la sélection des sites et enregistrer l'information en commentaire de réinstallation

## 📸 Captures d'écran
![image](https://user-images.githubusercontent.com/50863659/174827970-c188cb51-0de4-46e4-988f-c6c057bf329d.png)

## 🚨 Notes pour la mise en production
_Liste des choses à faire pour le déploiement (changement de configuration, migrations à faire tourner, etc.), si possible avec les éléments les plus précis possibles (commande exacte à exécuter, etc.)._

2022-06-29 15:19 UTC, anis requested changes
Bon, je suis désolé je n'ai pas tout relu vraiment dans le détail côté front, je n'arrivais plus trop à suivre tous les changements.
Commentaires à revoir ensemble.

2022-06-29 15:19 UTC, anis commented on packages/frontend/webapp/src/js/app/components/TownForm/utils/formatTown.js
> +            reinstallation_comments: data.reinstallationComments || undefined
il manque `location_shantytowns` du coup, non ? (que je renommerais, cf. commentaire côté api)

2022-06-29 15:19 UTC, anis commented on packages/frontend/webapp/src/js/app/components/TownForm/TownFormPanelLocation.vue
> +                } catch (err) {}
Pour moi, c'est une logique qui doit être déplacé côté API. Ce filtrage et cet ordonnancement ont plus de sens, il me semble, côté API que côté front.
Ca t'éviterait tellement de choses :
- le besoin de récupérer le département correspondant à la ville sélectionné (un appel API en moins)
- d'avoir à stocker et faire se balader `citycode`
- d'avoir à fetch la liste de tous les sites dans loaded
- d'avoir à parcourir la liste de tous les sites pour les filtrer (pas très performant côté front)
- etc.

2022-06-29 15:19 UTC, anis commented on packages/frontend/webapp/src/js/app/components/TownForm/inputs/InputAddress.vue
> +            this.$emit("change", [lat, lng, citycode]);
cf. mon commrentaire plus haut, mais pour moi tu peux te passer te citycode

2022-06-29 15:19 UTC, anis commented on packages/frontend/webapp/src/js/app/components/TownForm/TownFormPanelCharacteristics.vue
> +        "input.declaredAt": async function() {
pas besoin du `async`, et je déplacerait ce watch directement dans `TownForm` : je ne vois pas l'intérêt de surveiller cette valeur ici pour déclencher un événement alors que le parent peut directement surveiller la valeur lui-même

2022-06-29 15:19 UTC, anis commented on packages/frontend/webapp/src/js/app/components/TownForm/TownForm.vue
> +            this.town.characteristics.is_reinstallation = null;
Pas sûr de comprendre la logique ici ?
Si on a pas la date de déclaration, le site ne peut pas être une réinstallation ?

2022-06-29 15:19 UTC, anis commented on packages/frontend/webapp/src/js/app/components/TownForm/TownForm.vue
> +            return town;
Je pense que c'est à supprimer ça

2022-07-01 08:25 UTC, anis commented on packages/api/server/services/shantytown/create.js
> +        detailedClosedShantytowns = Promise.all(closedTowns.map(town => shantytownModel.findOne(user, JSON.stringify(town))))
Pas besoin de promise.all, juste une requête `findAll()` avec un filtre sur les identifiants

2022-07-22 07:24 UTC, ch-benard commented on packages/api/server/controllers/geoController.js
> +            });
```
services/geo
    getDepartementFromCityId()
      ✓ retourne le département
      ✓ renvoie une exception ServiceError 'fetch_failed'  si le departement n'existe pas en bdd
```

2022-07-25 14:37 UTC, ch-benard commented on packages/frontend/webapp/src/js/app/components/TownForm/TownForm.vue
> +            return town;
Effectivement.

2022-07-25 15:07 UTC, ch-benard commented on packages/frontend/webapp/src/js/app/components/TownForm/TownForm.vue
> +            this.town.characteristics.is_reinstallation = null;
Effectivement, ce n'est pas ce qui convient. SI la date de déclaration est supprimée ou modifiée, il faut recalculer la liste des sites fermés dans les 90 jours précédents dans le département du site en cours de déclaration. Ce qui nous ramène à ton commentaire précédent concernant le déplacement du calcul de cette liste côté API. Ce qui me permettra de recalculer la liste si l'adresse change OU si la date de signalement change.

2022-08-02 10:30 UTC, ch-benard commented on packages/frontend/webapp/src/js/app/components/TownForm/utils/formatTown.js
> +            reinstallation_comments: data.reinstallationComments || undefined
Non. pour l'instant, les sites fermés sont ajoutés dans le commentaire.

2022-09-09 14:03 UTC, closed without merging