#minor (1486) permettre de restreindre l'accès à un commentaire à une liste de structures ou d'utilisateurs
MTES-MCT/resorption-bidonvilles pull request #536
Opened 2022-06-22 06:16 UTC by gregoirethomazeau

## 🧾 Ticket Trello
https://trello.com/c/oDK1jBWt/1486-sur-le-journal-du-site-permettre-de-restreindre-lacc%C3%A8s-%C3%A0-un-commentaire-%C3%A0-une-liste-de-structures-ou-dutilisateurs-partie-r%C3%A9alis

## 🛠 Description de la PR
côté BDD : 
- création de deux tables en bdd: shantytown_comment_organization_access et shantytown_comment_user_access faisant la liaison entre shantytown_comments et les destinataires
- suppression de la permission 'listPrivate.shantytown_comment' pour les utilisateurs ayant le rôle direct_colaborator : les commentaires réservés Pref et DDETS sont maintenant gérés via la table shantytown_comment_organization_access. La permission est maintenue pour les administrateurs locaux ou nationaux

Côté API : 
- adaptation des différentes méthodes à cette nouvelle gestion des commentaires : createComment et findOne pour la création, getHistory pour l'historique, findAll pour l'export

Côté Front :
- Adaptation du formulaire (rajout d'un bouton radion,  champ d'autocompletion, liste des destinataires) 
- adaptation de l'affichage des destinataires dans le journal du site et les dernières activités

## 📸 Captures d'écran
<img width="916" alt="Capture d’écran 2022-06-22 à 08 15 31" src="https://user-images.githubusercontent.com/94321132/174956676-351c60be-2694-4a95-a0b6-a91ddb130b40.png">
<img width="941" alt="Capture d’écran 2022-06-22 à 08 16 12" src="https://user-images.githubusercontent.com/94321132/174956764-e4cf6122-ad61-41d5-858e-5d7ead3f1437.png">
<img width="1320" alt="Capture d’écran 2022-06-22 à 08 16 31" src="https://user-images.githubusercontent.com/94321132/174956805-70132ecd-46b6-47ed-aeb1-bbe18a4fed37.png">

## 🚨 Notes pour la mise en production
3 migrations à faire tourner

2022-06-22 09:42 UTC, ch-benard requested changes
Juste deux petits commentaires. Rien d'autre à signaler.

2022-06-22 09:42 UTC, ch-benard commented on packages/api/db/migrations/30000014-create_table_shantytown_comment_organization_access.js
> +        await Promise.all([
Le `Promise.all`est-il justifié dans la mesure où il n'y a qu'une promesse attendue ?
```
await queryInterface.dropTable('shantytown_comment_organization_access', { transaction });
```
devrait suffire ?

2022-06-22 09:42 UTC, ch-benard commented on packages/api/db/migrations/30000015-create_table_shantytown_comment_user_access.js
> +        await Promise.all([
Même commentaire que pour `shantytown_comment_organization_access`:
```
await queryInterface.dropTable('shantytown_comment_user_access', { transaction });
```
devrait sufffire.

2022-06-23 08:37 UTC, anis requested changes

2022-06-23 08:37 UTC, anis commented on packages/api/db/migrations/30000016-delete-listPrivate-shantytown_comment-direct_collaborator.js
> +};
Est-ce qu'il ne faudrait pas également supprimer la colonne "private" de "shantytown_comments" ?
J'ai l'impression que c'est un dupliqué d'une information qu'on a déjà : soit le commentaire est lié à un utilisateur et/ou une structure, et dans ce cas il est considéré comme privé, soit pas et donc il est public.

Le risque étant de se retrouver avec une colonne `private` incohérente vis-à-vis des utilisateurs/structures qui lui sont associés.

2022-06-23 08:37 UTC, anis commented on packages/api/server/controllers/shantytownCommentController/create.js
> +                privateChooseTarget: req.body.privateChooseTarget,
Théoriquement, il manque la partie `validator` pour ce paramètre : `validators/shantytownComment/create.js`, mais de mon point de vue il est même carrément supprimable.

En effet, soit il y a des targets (et dans ce cas là `privateChooseTarget`est true, soit targets est vide et dans ce cas `privateChooseTarget` est false).
En revanche il manque bien un validator pour `targets` qui s'assure que le paramètre est bien un tableau (et par défaut un tableau vide).

2022-06-23 08:37 UTC, anis commented on packages/api/server/models/shantytownCommentModel/create.js
> +        await Promise.all(
Il faudrait englober tous ces insert dans une transaction

2022-07-27 11:36 UTC, merged