#minor (1484)(1510) Qualifier le sujet d'un message du JdS + tag "Canicule"
MTES-MCT/resorption-bidonvilles pull request #547
Opened 2022-07-21 09:26 UTC by ch-benard

# PR IN DRAFT MODE BEFORE REBASE ON DEVELOP BRANCH

## 🧾 Tickets Trello
https://trello.com/c/7WWkNY3t
https://trello.com/c/BJtqiQ78

## 🛠 Description de la PR
- Création d'étiquettes ou "tags" permettant de qualifier chaque commentaire sur le journal des sites
- Ces tags sont classés en catégories. Pour l'instant il n'existe que deux catégories:
    - regular: ordinaire
    - covid: Covid
- Cette PR ne concerne que les tags de type "regular".
- Modèle de données:
![image](https://user-images.githubusercontent.com/50863659/180171226-e3c94e26-cc37-4cab-a12e-6bf75e8a7ff5.png)

### API
- Création des scripts de migrations, modèles, services et contrôleurs requis
- Adaptation des objets côté API impactés (modèle, service, contrôleur de `shantytownComment`)
- Mention des tags dans les notifications Mattermost de création des commentaires
- Ajout de la liste des tags aux commentaires sur l'export de la fiche "site"
- Ajout de la création des tags dans les tests
- Pour la carte 1510, ajout d'une migration pour créer le tag "Canicule"

### Frontend
- Ajout des tags sous forme de cases à cocher sur le formulaire de création du commentaire
- Ajout des tags des commentaires
- Pour la carte 1510, mise ne forme spécifique du tag "Canicule"

## 📸 Captures d'écran
- Sélection des tags
![image](https://user-images.githubusercontent.com/50863659/180179676-a2cebb48-5958-46d4-b353-051a30e94368.png)

- Messages tagués:
![image](https://user-images.githubusercontent.com/50863659/180179143-15a07dec-5110-4fd0-94a5-de491a763e3a.png)

## 🚨 Notes pour la mise en production
- Exécuter les migrations pour créer et peupler les tables concernées

2022-08-02 08:15 UTC, gregoirethomazeau requested changes

2022-08-02 09:12 UTC, gregoirethomazeau requested changes

2022-08-02 09:12 UTC, gregoirethomazeau commented on packages/api/server/services/shantytown/export/option_section_comments.js
> +                                        text: 'Aucun message n\'a été publié dans le journal du site',
je ne comprends pas le message 'Aucun message n\'a été publié dans le journal du site' dans ce contexte 
tu veux plutôt dire 'Aucun tag sur ce commentaire' ? mais peut-être n'est-ce même pas nécessaire

2022-08-02 09:13 UTC, gregoirethomazeau commented on packages/api/server/utils/mattermost.js
> +        channel: '#notif-dev-test',
tu l'as fait dans un commit après donc oublie ce commentaire ^^

2022-08-25 11:48 UTC, anis requested changes
Autres commentaires que je n'ai pas pu mettre car cela concernait des fichiers non modifiés :
- ne faudrait-il pas supporter les tags dans le modèle `shantytownCommentModel.findAll()`,  qui est utilisé pour l'export des commentaires ? (reservé aux admins donc non prioritaire mais je vois la demande venir)
-

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentTagModel/getTagsFromComment.js
> +module.exports = async (commentIds) => {
Je pense que c'est une erreur ici d'avoir accepté un tableau d'id : le nom de la fonction suppose qu'on ne cherche les tags que d'un seul commentaire ("Comment" au singulier) + tu retournes tous les tags de manière mélangée pour tous les commentaires de toute façon.

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownModel/_common/serializeComment.js
> +    serializedComment = Object.assign(
Quitte à réécrire ce bloc, j'en aurais profité pour supprimer le Object.assign et le remplacer par un spread (...), par soucis de cohérence avec le reste du code. :)

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownModel/_common/serializeComment.js
> +    const commentTags = await getTagsFromComment([comment.commentId]);
Je suis surpris que tu passes un tableau vu le nom de la fonction "FromComment" (au singulier)

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentTagModel/getTagsFromComment.js
> +            ctt.uid = ct.fk_comment_tag_type
Restons homogène sur l'écriture des requêtes SQL, partout ailleurs les left join sont écrits sur une seule ligne

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentTagModel/getTagsFromComment.js
> +    }, {});
Ce foreach aurait pu très facilement être remplacé par un
```js
return rows.map(tag => serializeCommentTag(tag));
```

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentTagModel/serializeCommentTag.js
> +        tagType: {
Un simple "type" ici aurait suffit, étant donné le contexte.
Par ailleurs, je note que c'est une donnée qui n'est utilisée nulle part côté front, donc on peut carrément la retirer (ici, comme dans la requête SQL).

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentTagModel/getTagsFromComment.js
> +            CONCAT(sct.fk_shantytown_comment, '-', sct.fk_comment_tag) as "shantytownCommentTagId",
Pas besoin de le select ici, car il n'est utile que pour le `ORDER`, autant écrire plus bas : `ORDER BY CONCAT(...)`

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentTagModel/getTagsFromComment.js
> +            ctt.uid = ct.fk_comment_tag_type
Voir ma remarque sur `serializeCommentTag` : le type est totalement inutilisé que ce soit côté API ou côté front, donc inutile de récupérer la donnée pour le moment.

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentTagModel/getTagsFromComment.js
> +            ctt.name AS "tagTypeLabel"
À retirer

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownCommentModel/findOne.js
> +                  sct.fk_shantytown_comment = sc.shantytown_comment_id
Par soucis d'homogénéité entre nos requêtes SQL, passer tout le left join sur une seule ligne

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownModel/_common/query.js
> +    promises.push(await getComments(user, Object.keys(serializedTowns.hash), true));
non, getComments retourne une promise (puisque c'est une fonction asynchrone) et c'est bien ce que l'on souhaite push dans promises.
avec le await, tu pushes le résultat de la promise dans le tableau promises, ce qui fait que le Promise.all() ne sert plus à rien.

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownModel/_common/getComments.js
> +                    )
indentation à corriger + left join à mettre sur une seule ligne

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownModel/_common/getComments.js
>      }, {});
Pour optimiser, réécrire en deux temps :
- une première boucle qui génère toutes les promises de serializeComment, et fait un await Promise.all(promises)
- une deuxième boucle, similaire à l'originale, qui push le commentaire sérialisé dans le tableau du site associé

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownModel/_common/serializeComment.js
> +    const commentTags = await getTagsFromComment([comment.commentId]);
Par ailleurs, pour des raisons de perf, je pense qu'il serait préférable qu'il n'y aie pas de requête SQL dans une fonction de serialisation.
C'est à la fonction qui demande la serialisation de fournir toutes les données nécessaires, et donc à se débrouiller pour fetch ces données en amont.

2022-08-25 11:48 UTC, anis commented on packages/api/server/models/shantytownModel/_common/serializeComment.js
> +    const commentTags = await getTagsFromComment([comment.commentId]);
Par ailleurs, pour des raisons de perf, je pense qu'il serait préférable qu'il n'y aie pas de requête SQL dans une fonction de serialisation.
C'est à la fonction qui demande la serialisation de fournir toutes les données nécessaires, et donc à se débrouiller pour fetch ces données en amont.

2022-08-25 11:48 UTC, anis commented on packages/api/test/suites/server/services/shantytownComment/createComment.spec.js
> +                expect(dependencies.createCommentTag).to.have.been.calledOnceWith(1, input.comment.tags.map(tag => tag.uid));
plutôt que d'écrire un "map", écrit les données en dur pour rendre le test moins "tautologique"

2022-08-25 11:48 UTC, anis commented on packages/api/test/suites/server/services/shantytownComment/createComment.spec.js
> +                    input.comment.tags.map(tag => tag.label),
même remarque

2022-08-25 11:48 UTC, anis commented on packages/api/test/suites/server/controllers/shantytownCommentController/create.spec.js
> +                        tagLabels: ['Conditions de vie', 'Passage sur site'],
tagLabels n'existe pas dans le body, si ?

2022-08-25 11:48 UTC, anis commented on packages/api/test/suites/server/controllers/shantytownCommentController/create.spec.js
> +                    tags: ['livingConditions', 'onSiteVisit'],
tags n'est pas censé être une liste de string, mais une liste d'objet

2022-08-25 11:48 UTC, anis commented on packages/frontend/webapp/src/js/app/components/RegularTag/specialTags.js
> +            class: "inline-block text-black bg-red300"
y a pas un mélange des genres bizarre avec le tag covid ?

2022-08-25 11:48 UTC, anis commented on packages/frontend/webapp/src/js/app/components/RegularTag/RegularTag.vue
> +            if (typeof resultat !== "undefined") {
`resultat !== undefined`

2022-08-25 11:48 UTC, anis commented on packages/frontend/webapp/src/js/app/components/RegularTag/specialTags.js
> +};
autant exporter le tableau directement non ? plutôt qu'un objet avec une clé

2022-08-25 11:48 UTC, anis commented on packages/frontend/webapp/src/js/app/components/RegularTag/RegularTag.vue
> +            return tagClass;
Tout ça peut être réécrit de façon "plus light" :
```js
const specialTag = specialTagsColl.specialTags.find(({ uid }) => uid === this.tag.uid);
if (specialTag !== undefined) {
    return specialTag.class;
}

return "text-black bg-blue300";
```

2022-08-30 13:11 UTC, merged