#minor (1626) Dans la page d'accueil, ajout de la barre de recherche d'un site
MTES-MCT/resorption-bidonvilles pull request #630
Opened 2022-11-03 10:46 UTC by gregoirethomazeau

## 🧾 Ticket Trello
https://trello.com/c/OEtrrhmR/1626-v1-mobile-dans-la-page-daccueil-ajout-de-la-barre-de-recherche-dun-site

## 🛠 Description de la PR
RAS

2022-11-04 14:28 UTC, anis requested changes

2022-11-04 14:28 UTC, anis commented on packages/frontend/mobile/src/js/pages/NotesForm/publication/NotesPublicationForm.vue
> +                        La note a déjà été publiée sur ce site: veuillez choisir
espace avant le `:`

2022-11-04 14:28 UTC, anis commented on packages/frontend/mobile/src/js/pages/NotesForm/publication/NotesPublicationForm.vue
> +            );
`this.note.publications.some`

2022-11-04 14:28 UTC, anis commented on packages/frontend/mobile/src/js/pages/NotesForm/NotesForm.vue
> +                        v-if="note.publications.length === 0"
pas de `v-if` mais un disabled me paraît mieux, non ?

2022-11-04 14:28 UTC, anis commented on packages/frontend/mobile/src/store/modules/notes.js
> +                ).length > 0
`.some`

2022-11-04 14:28 UTC, anis commented on packages/frontend/mobile/src/store/modules/towns.js
> +            }
je trouve toute cette logique un poil plus compliquée que nécessaire : en fait je crois qu'il n'y a pas besoin de stocker "detailedTown" dans le store pour deux raisons.
1- c'est une donnée vraiment complètement spécifique à la page "fiche site" et qui n'a pas besoin d'être conservée en mémoire quand on la quitte, donc ça peut être une simple computed dans la fiche site
2- c'est en réalité une donnée qu'on a déjà dans le "hash" et qu'on recopie dans une autre variable du store

Une façon plus simple pour moi serait de déporter côté fiche site en disant :
- la fiche site consulte le store : si le site est dans le hash, je l'utilise
- sinon, je provoque un fetch

2022-11-04 14:28 UTC, anis commented on packages/frontend/mobile/src/js/pages/NotesForm/publication/NotesPublicationForm.vue
> +                    </p>
Je laisse un commentaire ici pour être sûr d'y repenser mais : j'aurais bien aimé une capture d'écran de cet état, pour ne pas avoir à checkout la branche et simuler l'état pour le tester.
Idem pour le paragraphe au-dessus "La note a déjà été publiée sur ce site :".

2022-11-04 14:28 UTC, anis commented on packages/frontend/mobile/src/js/pages/NotesForm/NotesFormHeader.vue
> +        </div>
Une capture d'écran de ce à quoi ça ressemble aurait été cool

2022-11-07 09:46 UTC, gregoirethomazeau commented on packages/frontend/mobile/src/js/pages/NotesForm/NotesForm.vue
> +                        v-if="note.publications.length === 0"
il vaut mieux  mettre deux disabled  qu'un v-if/v-else d'après toi ?

2022-12-05 21:11 UTC, closed without merging