#minor (1909) étendre les droits d'export des sites à une date passée
MTES-MCT/resorption-bidonvilles pull request #807
Opened 2023-07-05 08:31 UTC by ch-benard

## 🧾 Ticket Trello
https://trello.com/c/u58JdhF1

## 🛠 Description de la PR
- Ajout d'une migration qui étend le droit d'exporter la liste des sites à une date passée aux rôles ayant le droit d'export des sites.
- La migration `down` supprime le droit d'export à une date passée à tous les rôles sauf  'national_admin' qui était le seul à disposer de ce droit avant l'exécution de la migration `up`

## 🚨 Notes pour la mise en production
- Exécuter la migration `30000062-01-extend-shantytown_history-export-permissions.js`

2023-07-06 09:30 UTC, anis commented on packages/api/server/services/shantytown/exportTown.ts
> -    }
Attention, ici il faudrait appliquer la permission shantytown_history, sinon la permission en question n'est jamais utilisée ailleurs que côté front et n'a donc plus aucune utilité.
Soit on applique la permission ici, si c'est une date passée, soit on retire tout simplement la permission shantytown_history et un export autorise un export passé également.

2023-07-06 09:43 UTC, ch-benard commented on packages/api/server/services/shantytown/exportTown.ts
> -    }
Effectivement ! C'est corrigé.

2023-07-17 15:56 UTC, anis commented on packages/api/server/services/shantytown/exportTown.spec.ts
> +
inverser la logique et vérifier que si "can" retourne false, alors on obtient bien un ServiceError

2023-07-17 15:57 UTC, anis commented on packages/api/db/migrations/30000062-01-extend-shantytown_history-export-permissions.js
> +        return transaction.commit();
manque le rollback

2023-07-17 16:09 UTC, anis commented on packages/api/db/migrations/30000062-01-extend-shantytown_history-export-permissions.js
> +            }
factorisable + else if non nécessaire + isEmpty peut être remplacé par `permission.* !== null`

2023-07-17 16:10 UTC, anis requested changes
Quelques petits commentaires

2023-07-31 09:45 UTC, merged