#minor (2056) Permettre aux administrateurs nationaux et aux propriétaire d'une question de la modifier
MTES-MCT/resorption-bidonvilles pull request #939
Opened 2024-02-13 17:05 UTC by superfeedboy

## 🧾 Ticket Trello
https://trello.com/c/D4us8f30/2056

## 🛠 Description de la PR
Ajout d'une fonctionnalité de modification de question par les administrateurs nationaux et le propriétaire de ladite question.

## 📸 Captures d'écran
Champs bloqués:
![image](https://github.com/MTES-MCT/resorption-bidonvilles/assets/34971399/4fccf577-da7b-444f-b0b6-60c457403ca3)
Champs modifiables:
![image](https://github.com/MTES-MCT/resorption-bidonvilles/assets/34971399/960a7caf-dc7c-4f78-ad92-018c3ba89fa5)

## 🚨 Notes pour la mise en production
Migration à effectuer pour ajouter les colonnes et liens utiles.

2024-02-15 16:16 UTC, anis commented on packages/api/server/controllers/question/update/question.update.validator.ts
> +                let fullTags;
typer fullTags

2024-02-15 16:17 UTC, anis commented on packages/api/server/controllers/question/update/question.update.validator.ts
> +        .exists({ checkNull: true }).bail().withMessage('La question est obligatoire')
optional

2024-02-15 16:17 UTC, anis commented on packages/api/server/controllers/question/update/question.update.validator.ts
> +        .exists({ checkNull: true }).bail().withMessage('Le détail de la question est obligatoire')
optional

2024-02-15 16:21 UTC, anis commented on packages/api/server/controllers/question/update/question.update.validator.ts
> +export default [
rajouter un contrôle de param(id), qui s'assure que l'id correspond bien à une question existante en base
```ts
param('id')
    .toInt()
    .custom(async (value, { req }) => {
        let question;
        try {
            question = await questionModel.fetch(value);
        } catch (error) {
            throw new Error('Une erreur de lecture en base de données est survenue');
        }

        // bla bla
    }),
```

2024-02-15 16:22 UTC, anis commented on packages/api/server/controllers/question/update/question.update.ts
> +export default async (req, res, next) => {
typer req :
```ts
interface QuestionUpdateRequest extends Request {
    user: User;
    body: {
        question_id: number;
    },
    // etc.
}
```

2024-02-15 16:23 UTC, anis commented on packages/api/server/controllers/question/update/question.update.ts
> +        const question = await questionService.findOne(req.body.question_id);
si le validator valide le param `id`, tu peux récupérer la question déjà fetch : `req.question`

2024-02-15 16:37 UTC, anis commented on packages/api/server/models/questionModel/serializeQuestion.ts
> +        },
Mettre à jour pour utiliser `question.questionUpdatedBy` etc.

2024-02-15 16:38 UTC, anis commented on packages/api/server/models/questionModel/update.ts
> +    }
ça peut être remplacé par un `questionModel.findOne(data.question_id, transaction)`

2024-02-15 16:44 UTC, anis commented on packages/api/server/models/questionModel/QuestionInput.d.ts
> +
```ts
export type UpdateQuestionInput = Partial<BaseQuestionInput> & {
    question_id: number;
    updated_by: number;
};
```

2024-02-15 16:46 UTC, anis commented on packages/api/types/resources/UpdatedQuestion.d.ts
> +};
je soupçonne que ce type ne sera plus nécessaire, si le modèle `update` retourne directement une `Question`

2024-02-15 16:47 UTC, anis commented on packages/api/types/resources/QuestionUpdatedBy.d.ts
> +export type QuestionUpdatedBy = BaseQuestionUpdate | FullQuestionUpdate;
je soupçonne que ce type ne sera plus nécessaire, si le modèle update retourne directement une Question

2024-02-15 16:48 UTC, anis commented on packages/api/server/services/question/update.spec.ts
> +        // console.log('Expected:', expectedResult);
à supprimer

2024-02-15 16:51 UTC, anis commented on packages/api/server/services/question/update.spec.ts
> +        };
si le service est modifié pour retourner une `Question`, j'utiliserais l'utilitaire `serialized` de `test/utils/question` pour créer une fausse question ici, plutôt qu'un partial :
```ts
import { serialized as fakeQuestion } from '#test/utils/question';

...

const expectedResult = fakeQuestion({
    id: 42,
    // ...
});
```

2024-02-15 16:54 UTC, anis commented on packages/api/server/services/question/update.spec.ts
> +        expect(result).to.eql(expectedResult);
j'aurais peut-être fait un cas de test séparé juste pour ce expect

2024-02-15 16:58 UTC, anis commented on packages/api/server/controllers/question/update/question.update.route.ts
> +    app.customRoutes.patch('/question/:id', controller, validator, {
passer `question` au pluriel pour respecter la nomenclature en place

2024-02-15 16:58 UTC, anis commented on packages/frontend/webapp/src/api/questions.api.js
> +}
passer `question` au pluriel pour respecter la nomenclature en place

2024-02-15 16:59 UTC, anis commented on packages/frontend/ui/src/components/Input/Checkbox.vue
> +    disabledCheckbox: Boolean,
pourquoi pas`disabled` ?

2024-02-15 17:01 UTC, anis commented on packages/frontend/ui/src/components/Input/TextArea.vue
> +        },
????

2024-02-15 17:03 UTC, anis commented on packages/frontend/webapp/src/helpers/router.js
> +        },
ordre alphabétique b*****

2024-02-15 17:05 UTC, anis commented on packages/frontend/webapp/src/views/MiseAJourDeQuestionView.vue
> +            <FormNouvelleQuestion ref="form" :question="question" mode="edit" />
`mode="edit"` ne me semble pas nécessaire

2024-02-15 17:07 UTC, anis commented on packages/frontend/webapp/src/stores/questions.store.js
> +        };
si l'API répond une question entière, on peut remplacer directement l'objet plutôt que de faire de la déstructuration

2024-02-15 17:11 UTC, anis commented on packages/frontend/webapp/src/components/FormNouvelleQuestion/FormNouvelleQuestion.vue
> +            // );
à supprimer

2024-02-15 17:17 UTC, anis commented on packages/frontend/webapp/src/components/FormNouvelleQuestion/FormNouvelleQuestion.schema.js
> +}
ce schema n'a pas besoin d'être une fonction

2024-02-15 17:22 UTC, anis requested changes
Du beau boulot, quelques simplifications possibles tout de même !

2024-02-20 08:37 UTC, superfeedboy commented on packages/api/types/resources/Question.d.ts
> +    } | null,
Intégration des données récupérées suite à la modification des models pour findOne et findAll.
Les objets renvoyés contiennent maintenant:
- cas de question modifiée: `updateBy: { objet complet de l'utilisateur + organsation }`
- cas de question non modifiée: `updatedBy: null`

2024-02-20 10:58 UTC, superfeedboy commented on packages/api/server/services/question/update.ts
Modification du typage pour traiter une Question plutôt qu'une UpdatedQuestion

2024-02-20 15:48 UTC, merged